#!/bin/bash

if [ ! -f /root/.pw ]; then
	rootpasswd=$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 12)
	printf '%s' $rootpasswd >/root/.pw
	(echo $rootpasswd; echo $rootpasswd) | passwd root
else
	passwd -d root
fi
