#!/bin/bash

arch_name=$(uname -m)
case "$arch_name" in
    "aarch64")
        arch_name="arm64"
        ;;
    "amd64")
        arch_name="x86_64"
        ;;
esac
grub-install --target=${arch_name}-efi --bootloader-id=grub --removable \
    --recheck --efi-dir=/boot/efi
grub-mkconfig -o /boot/grub/grub.cfg
