IMAGE_NAME = ubuntu
IMAGE_VERSION = artful
IMAGE_VERSION_ALIASES = 17.10
IMAGE_TITLE = Ubuntu Artful Aardvark
IMAGE_DESCRIPTION = Ubuntu Artful Aardvark (17.10)
IMAGE_SOURCE_URL = https://github.com/scaleway/image-ubuntu
IMAGE_VENDOR_URL = http://www.ubuntu.com
IMAGE_BOOTSCRIPT = mainline 4.14
IMAGE_BASE_FLAVORS = common docker-based systemd feature-motd
